#!/bin/sh

bitbake --postread conf/toaster.conf --server-only -t xmlrpc -B localhost:0 && export BBSERVER=localhost:-1
nohup bitbake --observe-only -u toasterui >/opt/yocto/build/share/toaster/toaster_ui.log &

